### ISSUE TITLE
Error after typing "using MathLink"

### ISSUE THREAD

**Issue by bernie-wu** [JuliaInterop/MathLink.jl#34] opened 2020-02-11 08:13 UTC
When I type `using MathLink` into my julia terminal, the following error occurs. I've even tried to add the relevant paths as mentioned in the readme but the error still shows up. What could be wrong? I'm using Mathematica version 12 and julia version 1.3.1.

> ERROR: InitError: error compiling __init__: could not load library ""
>The specified module could not be found.
>Stacktrace:
> [1] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:692                              [2] >_require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:776                         [3] >_require(::Base.PkgId) at .\loading.jl:1001
> [4] require(::Base.PkgId) at .\loading.jl:922
> [5] require(::Module, ::Symbol) at .\loading.jl:917
>during initialization of module MathLink
>caused by [exception 1]
>could not load library ""
>The specified module could not be found.
>Stacktrace:
> [1] _include_from_serialized(::String, ::Array{Any,1}) at .\loading.jl:692
> [2] _require_search_from_serialized(::Base.PkgId, ::String) at .\loading.jl:776
> [3] _require(::Base.PkgId) at .\loading.jl:1001
> [4] require(::Base.PkgId) at .\loading.jl:922
> [5] require(::Module, ::Symbol) at .\loading.jl:917

**Comment by zwwi** [comment] 2020-02-13 14:56
I have the same issue. working on windows

**Comment by simonbyrne** [comment] 2020-03-20 18:16
Sounds like a duplicate of #30.

**Closed by simonbyrne** 2020-03-20 18:16 UTC
